version: '3.4'

services:
    kurjeris:
        image: kurjeris
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: Kurjeris
            DB_USERNAME: laravel
            DB_PASSWORD: 1234

    db:
        image: "mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: Kurjeris
            MYSQL_USER: laravel
            MYSQL_PASSWORD: 1234
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
